###
# Encode session video for label studio
POST http://localhost:5011/api/processing/encode/video/label-studio
Content-Type: application/json

{
    "video_path": "/Users/bubz/Developer/master-project/aolme-datastore/cohort-2/level-2/school-polk/group-C/20180612/video/session_video.mp4",
    "output_path": "/Users/bubz/Developer/master-project/aolme-datastore/cohort-2/level-2/school-polk/group-C/20180612/video/session_video_encode.mp4"

}

###
#Create Session Video
POST http://localhost:5011/api/processing/session_video
Content-Type: application/json

{
    "video_list_path": "/Users/bubz/Developer/master-project/aolme-datastore/cohort-2/level-2/school-polk/group-C/20180612/video",
    "output_file_path": "/Users/bubz/Developer/master-project/aolme-datastore/cohort-2/level-2/school-polk/group-C/20180612/video/session_video.mp4",
    "fps": 30,
    "shape": [858, 480]

}
###
POST http://localhost:5010/api/create
Content-Type: application/json

{
    "table_name": "datastore",
    "service": "datastore-management-service",
    "request_id": "ABC123",
    "payload": {
      "name":"test_datastore_1",
      "description": "test datastore desc",
      "path": "/test/path"  
    }

}